# 为应用起个名字
Spring:
  application:
    name: spserver
  #安全验证
  security:
    user:
      name: user
      password: 123456
# 设置端口号
server:
  port: 9000
# 配置注册中心Eureka
eureka:
  instance:
    hostname: 172.25.20.125
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  server:
    renewal-percent-threshold: 0.5
    enable-self-preservation: true
  #配置Eureka 客户端
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中 默认是true
    fetchRegistry: false       #是否从Eureka服务中获取注册信息 默认是true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://name:password@172.25.20.125:9000/eureka/